[server]
# Performance optimizations
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true
enableRunOnSave = false
enableDataFrameCache = true
enableDataFrameCache = true

[browser]
gatherUsageStats = false
showErrorDetails = false

[theme]
base = "light"
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
showErrorDetails = false
showWarningOnDirectExecution = false

[runner]
# Performance settings
magicEnabled = false
installTracer = false
fixMatplotlib = true

[logger]
level = "warning"
messageFormat = "%(asctime)s %(message)s"

[deprecation]
showfileUploaderEncoding = false
showPyplotGlobalUse = false
